CREATE TABLE IF NOT EXISTS defect_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TEXT,
  image_id TEXT,
  product_type TEXT,
  defect_detected INTEGER,
  defect_type TEXT,
  defect_category TEXT,
  severity TEXT,
  confidence REAL,
  location TEXT,
  region_horizontal TEXT,
  region_vertical TEXT,
  action_taken TEXT,
  line_id TEXT,
  shift TEXT,
  processing_ms INTEGER,
  model_name TEXT,
  visual_explanation TEXT,
  possible_causes TEXT,
  recommended_fix TEXT,
  prevention TEXT,
  factory_owner_summary TEXT
);
